package:
  name: libspiro
  version: 1.3.0

source:
  url: https://github.com/fontforge/libspiro/releases/download/20221101/libspiro-dist-20221101.tar.gz
  sha256: 5984fb5af3e4e1f927f3a74850b705a711fb86284802a5e6170b09786440e8be

build:
  run_exports:
    - libspiro

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - make

about:
  home: https://github.com/fontforge/libspiro
  license: GPL-3.0+
  license_file: COPYING
  summary: >
    Spiro is the creation of Raph Levien. It simplifies the drawing of
    beautiful curves.
